Repository palantir/metric-schema, pull requests merged in 2019-12, with the labels that each got.

#26 Stable markdown order regardless of the input schema order
  changelog/@unreleased/pr-26.v2.yml
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: autorelease, merge when ready

#28 Provide stable markdown order when a namespace is defined twice
  changelog/@unreleased/pr-28.v2.yml
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: autorelease, merge when ready

#32 Exclude version in generated markdown
  changelog/@unreleased/pr-32.v2.yml
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: autorelease, merge when ready

#36 support eclipse
  changelog/@unreleased/pr-36.v2.yml
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaPlugin.java
Labels: autorelease, merge when ready

#37 mark all tasks as cacheable
  changelog/@unreleased/pr-37.v2.yml
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CompileMetricSchemaTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CreateMetricsManifestTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/GenerateMetricMarkdownTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/GenerateMetricSchemaTask.java
Labels: autorelease, merge when ready

#39 Test coverage for MarkdownRenderer utility functions
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: merge when ready, no changelog

#43 Fix markdown rendering sort order to prioritize local metrics
  changelog/@unreleased/pr-43.v2.yml
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: autorelease, merge when ready

#50 Generated utilities use TaggedMetricRegistry.registerWithReplacement
  changelog/@unreleased/pr-50.v2.yml
  gradle-metric-schema/src/test/groovy/com/palantir/metric/schema/gradle/Versions.groovy
  metric-schema-java/src/integrationInput/java/com/palantir/test/MyNamespaceMetrics.java
  metric-schema-java/src/integrationInput/java/com/palantir/test/ReservedConflictMetrics.java
  metric-schema-java/src/integrationInput/java/com/palantir/test/ServerMetrics.java
  metric-schema-java/src/main/java/com/palantir/metric/schema/MetricTypes.java
  metric-schema-java/src/main/java/com/palantir/metric/schema/UtilityGenerator.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#53 Upgrade to tritium 0.16.3
  changelog/@unreleased/pr-53.v2.yml
  gradle-metric-schema/src/test/groovy/com/palantir/metric/schema/gradle/Versions.groovy
  versions.lock
  versions.props
Labels: merge when ready

#54 Use TaggedMetricRegistry.registerWithReplacement for all gauges
  changelog/@unreleased/pr-54.v2.yml
  metric-schema-java/src/integrationInput/java/com/palantir/test/ReservedConflictMetrics.java
  metric-schema-java/src/integrationInput/java/com/palantir/test/VisibilityMetrics.java
  metric-schema-java/src/main/java/com/palantir/metric/schema/UtilityGenerator.java
Labels: merge when ready
