Repository palantir/metric-schema, pull requests merged in 2019-11, with the labels that each got.

#3 Publish the metric-schema plugin
  build.gradle
  gradle-metric-schema/build.gradle
  gradle-metric-schema/src/main/resources/META-INF/gradle-plugins/com.palantir.metric-schema.properties
Labels: merge when ready, no changelog

#8 document options in README
  README.md
Labels: merge when ready, no changelog

#13 Document IDE setup
  README.md
Labels: merge when ready, no changelog

#15 Expose standalone markdown plugin
  changelog/@unreleased/pr-15.v2.yml
  gradle-metric-schema/build.gradle
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaMarkdownPlugin.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaPlugin.java
  gradle-metric-schema/src/main/resources/META-INF/gradle-plugins/com.palantir.metric-schema-markdown.properties
  gradle-metric-schema/src/test/groovy/com/palantir/metric/schema/gradle/GenerateMetricMarkdownIntegrationSpec.groovy
Labels: autorelease, merge when ready

#16 CreateMetricsManifestTask avoids logging noisy stack traces
  changelog/@unreleased/pr-16.v2.yml
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CreateMetricsManifestTask.java
Labels: autorelease, merge when ready

#18 add standard PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge when ready, no changelog

#17 Metric manifest contains source of all schemas
  changelog/@unreleased/pr-17.v2.yml
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CreateMetricsManifestTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/GenerateMetricMarkdownTask.java
  gradle-metric-schema/src/test/groovy/com/palantir/metric/schema/gradle/MetricSchemaPluginIntegrationSpec.groovy
  gradle-metric-schema/src/test/resources/a-1.0.jar
  metric-schema-markdown/src/main/java/com/palantir/metric/schema/markdown/MarkdownRenderer.java
  metric-schema-markdown/src/test/java/com/palantir/metric/schema/markdown/MarkdownRendererTest.java
Labels: merge when ready
