Repository palantir/metric-schema, pull requests merged in 2024-02, with the labels that each got.

#1092 MetricSchemaPlugin declares sourcesJar dependency on metric generation
  build.gradle
  changelog/@unreleased/pr-1092.v2.yml
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CheckMetricMarkdownTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/CreateMetricsManifestTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/GenerateMetricMarkdownTask.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaPlugin.java
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/ObjectMappers.java
  metric-schema-lang/src/main/java/com/palantir/metric/schema/lang/TagDefinition.java
  metric-schema-lang/src/main/java/com/palantir/metric/schema/lang/TagValue.java
Labels: merge when ready, autorelease

#1100 Use task output as Java source directory
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaPlugin.java
Labels: no changelog, merge when ready, autorelease

#1101 Minor clean up
  gradle-metric-schema/src/main/java/com/palantir/metric/schema/gradle/MetricSchemaPlugin.java
Labels: no changelog, merge when ready
